package com.sangura.ruralconnect.agentService.enums;

public enum Region {
    MOMBASA, KWALE, KILIFI, TANA_RIVER, LAMU, TAITA_TAVETA, GARISSA, WAJIR, MANDERA, MARSABIT, ISIOLO, MERU, THARAKA_NITHI, EMBU, KITUI, MACHAKOS, MAKUENI, NYANZA, NYANDARUA, LAIKIPIA, NAKURU, NAROK, KAJIADO, KERICHO, BOMET, KAKAMEGA, VIHIGA, BUNGOMA, BUSIA, SIAYA, KISUMU, HOMA_BAY, MIGORI, KISII, NYAMIRA, TRANS_NZOIA, UASIN_GISHU, ELGEYO_MARAKWET, NANDI, BARINGO, WEST_POKOT, TURKANA, SAMBURU, NAIROBI, MURANGA, KIAMBU, KIRINYAGA;
}
